name: "peoplenet"
platform: "tensorrt_plan"
max_batch_size: 16
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 632, 1200 ]
  }
]
output [
  {
        name: "output_bbox/BiasAdd"
        data_type: TYPE_FP32
        dims: [ 12, 40, 75]
    },
    {
        name: "output_cov/Sigmoid"
        data_type: TYPE_FP32
        dims: [ 3, 40, 75]
    }
]
dynamic_batching { }
version_policy: {
  specific {
    versions: [ 1 ]
  }
}
